### ISSUE TITLE
Use windows when running from Cmder

### ISSUE THREAD

**Issue by aeberdinelli** [charlesguse/run-script-os#11]
Based on [this PR](https://github.com/charlesguse/run-script-os/issues/7), it will assume linux when running on cygwin. 

But there are cases where you are running cygwin without the bash syntax, and will cause some issues, for example:
![error](https://user-images.githubusercontent.com/1413883/51040794-2bc3ad80-1597-11e9-901d-b25f12d6cb30.PNG)

I've created a quick check to detect if Cmder is installed in which case will assume Windows (checking if a ENV var declared by Cmder exists) and it seems to be working:
![working](https://user-images.githubusercontent.com/1413883/51040841-472eb880-1597-11e9-828a-fe72a130e8ee.PNG)

I will submit a PR if you wish to include it in your codebase

**Comment by blalasaadri** [comment]
Actually, the changes in  [this PR](https://github.com/charlesguse/run-script-os/issues/7) are breaking changes; especially when combined with [pre-commit](https://www.npmjs.com/package/pre-commit) it detects Linux as an OS, even when run on Windows within PowerShell. As far as I can tell this is due to the fact, that bash is available - even when it shouldn't be used.
We switched to version 1.0.3 to fix this behaviour. A nicer solution however would probably be to let the user choose, how to act on windows systems if bash is detected - maybe by adding `:bash` or something similar as a separate goal (which would behave like `:win32` currently does and switching `:win32` back to how it acted before that change).

**Comment by GordonSmith** [comment]
Quick me too - running within git-bash on windows results in the "linux" variant to be called...

**Comment by mathiscode** [comment]
I'm sorry I didn't see this sooner! Thanks to @GordonSmith for commenting on #7 and getting my attention.

I've submitted PR #19 that allows this behavior to be overridden with RUN_OS_WINBASH=true.

**EDIT:** After digging around some more, @blalasaadri is absolutely right that #8 is a breaking change. I have changed PR #19 so that this is no longer default behavior, and cygwin/git bash users can set RUN_OS_WINBASH_IS_LINUX=true to trigger it if needed.

Do you feel like this addresses the issue?

**Comment by mathiscode** [comment]
@aeberdinelli Sorry I didn't see your PR #12 before submitting mine. I think #19 allows for fixing this problem on any shell and isn't specific to cmder.

**Comment by aeberdinelli** [comment]
Yeah that's a better approach since we're not assuming anything but letting the final user configure it. That looks good to me! 👍 😄
