### ISSUE TITLE
missing script: start:win32

### ISSUE THREAD

**Issue by josephi** [charlesguse/run-script-os#15]
Hi
My package.json looks like this:
![image](https://user-images.githubusercontent.com/2021378/51904729-0ec91000-23c8-11e9-8a3d-ad86e986ecff.png)

But it seems that if I don't create a `start:win32` to follow the `prestart:win32` command it fails.

**Comment by mathiscode** [comment]
I played around with this a bit, and I see the issue, but I can't quite find a way around it.

I tried changing run-script-os to use the regular start script (rather than platform-specific), but this leads to an infinite loop where npm just keeps executing the prestart script.

I couldn't find a way to prevent npm from executing the prestart, either. I found [this post](https://npm.community/t/add-ignore-script-scripts/4169) on [npm.community](https://npm.community) where they discuss an idea that may make this possible but so far it seems like it's a dead idea there.

I think the easiest workaround is to specify a start:* script that does nothing:

```json
"scripts": {
  "prestart": "run-script-os",
  "prestart:win32": "cls && npm run vendor",
  "prestart:darwin:linux": "clear && npm run vendor",
  "start": "npm run watch",
  "start:win32:linux:darwin": "cd ."
}
```

The `cd .` acts as a sort of cross-platform no-op so run-script-os can successfully run the script without it actually doing anything.

I'm sure you solved your problem months ago, but for anyone else that happens to stumble across this, this is what I would do if I just wanted to clear the screen:

```json
"scripts": {
  "clear-screen": "node -e \"console.clear()\"",
  "prestart": "npm run clear-screen && npm run vendor",
  "start": "npm run watch"
}
```

**Comment by josephi** [comment]
> I played around with this a bit, and I see the issue, but I can't quite find a way around it.
> 
> I tried changing run-script-os to use the regular start script (rather than platform-specific), but this leads to an infinite loop where npm just keeps executing the prestart script.
> 
> I couldn't find a way to prevent npm from executing the prestart, either. I found [this post](https://npm.community/t/add-ignore-script-scripts/4169) on [npm.community](https://npm.community) where they discuss an idea that may make this possible but so far it seems like it's a dead idea there.
> 
> I think the easiest workaround is to specify a start:* script that does nothing:
> 
> ```json
> "scripts": {
>   "prestart": "run-script-os",
>   "prestart:win32": "cls && npm run vendor",
>   "prestart:darwin:linux": "clear && npm run vendor",
>   "start": "npm run watch",
>   "start:win32:linux:darwin": "cd ."
> }
> ```
> 
> The `cd .` acts as a sort of cross-platform no-op so run-script-os can successfully run the script without it actually doing anything.
> 
> I'm sure you solved your problem months ago, but for anyone else that happens to stumble across this, this is what I would do if I just wanted to clear the screen:
> 
> ```json
> "scripts": {
>   "clear-screen": "node -e \"console.clear()\"",
>   "prestart": "npm run clear-screen && npm run vendor",
>   "start": "npm run watch"
> }
> ```

Thanks for your response
