### ISSUE TITLE
run-script-os does not work on npm 7.1.0

### ISSUE THREAD

**Issue by lpic10** [charlesguse/run-script-os#34]
The environment variable `npm_config_argv` is not available anymore: 
https://github.com/npm/rfcs/blob/latest/implemented/0021-reduce-lifecycle-script-environment.md

The alternative it seems is to use `npm_command` and `npm_lifecycle_event` instead.

**Comment by bulatenkom** [comment]
As a dirty fix, you can get `run-script-os` working, just by putting this line: 
```js
let options = [process.env["npm_command"], process.env["npm_lifecycle_event"]];
```
instead of
https://github.com/charlesguse/run-script-os/blob/03dbb78b240300255f654f8dc0b8dd29cd269d49/index.js#L43-L44
and omitting this check:
https://github.com/charlesguse/run-script-os/blob/03dbb78b240300255f654f8dc0b8dd29cd269d49/index.js#L14-L17

Caution. It will work just in case you use `npm > 7.0`, otherwise stay with previous npm versions. If something won't work, just reinstall `run-script-os` and downgrade to `npm@6.x`

**Comment by ncovercash** [comment]
You could make this a PR (maybe add an if-else for the NPM version so it wouldn't break anything existing)

**Comment by charlesguse** [comment]
Thank you for bringing this to my attention @lpic10 and thanks for the detailed thought on a quick fix @bulatenkom.

As @ncovercash mentioned, if someone would like to add a PR to fix this, that would be great.

I've just added automated testing to this repository but it isn't checking different versions of NPM yet. Clearly we will need to have some tests that check the different versions of NPM. I will, at some point, add the tests for different versions of NPM and get a fix in place but if someone wants to add it first, I would be happy to accept the PR!

**Comment by jamesmstone** [comment]
While you wait for this to be officially merged you can change to use my version by changing your package.json to look like this:
```
    "run-script-os": "github:jamesmstone/run-script-os",
 ```

**Comment by charlesguse** [comment]
This has been fixed with the most recent release of run-script-os (1.1.5)
